apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@db-svc:5432/tasktracker"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
